const mix = require('laravel-mix');

mix.copy(['node_modules/smartwizard/dist/css/smart_wizard_all.min.css', 'node_modules/smartwizard/dist/js/*.min.js'], 'plugins/smartwizard')
   .copy('node_modules/@fortawesome/fontawesome-free/css/all.min.css', 'plugins/fontawesome-free/css/all.min.css')
   .copy('node_modules/@fortawesome/fontawesome-free/webfonts/', 'plugins/fontawesome-free/webfonts', false)
   .copy('node_modules/@fullcalendar/bootstrap/', 'plugins/fullcalendar-bootstrap', false)
   .copy('node_modules/@fullcalendar/core/', 'plugins/fullcalendar', false)
   .copy('node_modules/@fullcalendar/daygrid/', 'plugins/fullcalendar-daygrid', false)
   .copy('node_modules/@fullcalendar/interaction/', 'plugins/fullcalendar-interaction', false)
   .copy('node_modules/@fullcalendar/timegrid/', 'plugins/fullcalendar-timegrid', false)
   .copy('node_modules/@ttskch/select2-bootstrap4-theme/dist/', 'plugins/select2-bootstrap4-theme')
   .copy('node_modules/bootstrap/dist/js/bootstrap.bundle.min.js', 'plugins/bootstrap/js/bootstrap.bundle.min.js')
   .copy('node_modules/bootstrap4-duallistbox/dist/*.*', 'plugins/bootstrap4-duallistbox')
   .copy('node_modules/bootstrap-switch/dist/', 'plugins/bootstrap-switch', false)
   .copy('node_modules/fontawesome-iconpicker/dist/', 'plugins/fontawesome-iconpicker', false)
   .copy('node_modules/fullscreenbookblock/', 'plugins/fullscreenbookblock', false)
   .copy('node_modules/icheck-bootstrap/icheck-bootstrap.min.css', 'plugins/icheck-bootstrap/icheck-bootstrap.min.css')
   .copy('node_modules/jquery/dist/jquery.min.js', 'plugins/jquery/jquery.min.js')
   .copy('node_modules/jquery-confirm/dist/*.*', 'plugins/jquery-confirm')
   .copy('node_modules/jquery-maskmoney/dist/jquery.maskMoney.min.js', 'plugins/jquery-maskmoney/jquery.maskMoney.min.js')
   .copy('node_modules/jquery-mask-plugin/dist/*.*', 'plugins/jquery-mask-plugin')
   .copy('node_modules/jquery-ui-dist/*.min.*', 'plugins/jquery-ui')
   .copy('node_modules/jstree/dist/', 'plugins/jstree', false)
   .copy('node_modules/jstree-bootstrap-theme/dist/', 'plugins/jstree-bootstrap-theme', false)
   .copy('node_modules/popper.js/dist/', 'plugins/popper', false)
   .copy('node_modules/raphael/*.min.js', 'plugins/raphael')
   .copy('node_modules/select2/dist/', 'plugins/select2', false)
   .copy('node_modules/summernote/dist/', 'plugins/summernote', false)
   .copy('node_modules/three-dots/dist/*.*', 'plugins/three-dots')
   .copy('node_modules/toastr/build/*.*', 'plugins/toastr')
   .js('dist/js/erp.datatable.js', 'dist/js/erp.datatable.min.js')
   .js('node_modules/jqdoublescroll/jquery.doubleScroll.js', 'plugins/jqdoublescroll/jquery.doubleScroll.min.js')
   .js('node_modules/jquery-mousewheel/jquery.mousewheel.js', 'plugins/jquery-mousewheel/jquery.mousewheel.min.js')
   .minify('dist/css/erp.css', 'dist/css/erp.min.css');
